### ISSUE TITLE
Usage details

### ISSUE THREAD

**Issue by garousiamir** [iamntz/yeoman-carbon-field-generator#1]
Hi, 
thanks for creating this but I'm confused on how to use it. can you tell me where to clone this repo exactly ? I have a plugin which I used carbon fields to generate some options for it. now I want to know that how can I use this tool to improve the speed of my development but I could run it yet. I would be grateful if you explain the usage in an example senario.
Thanks in advance

**Comment by iamntz** [comment]
@garousiamir hey, It's been quite a while since I last used this, so I can't tell you _exactly_ what you have to do.

> where to clone this repo exactly 
Actually, you can clone anywhere on your disk, AFAIK, this line should take care of linking things in the right place:

```
npm link
```
